<div id="content_story">
    <p>
        Story of Viking characters
        Vikings living in Northern Europe worship the god Odin and they believe that after death they will be able to drink beer and live with the gods in the temple of Valhalla, this makes the Vikings become brave people who are not afraid of the bad. died. After being exiled to the cold northern lands and settling in Balti, Olaf Haraldsson, the first Viking lord, led them east to conquer new lands.
        Ragnar Lothbrok, whose blue eyes are said to be bestowed by the gods, does not think so, he wants to move to the West where there are rich and rich lands, this disagreement has caused a feud for the two Ragnar Lothbrok and Olaf Haraldsso later. With the help of Bishop Heahumund a boat builder, Ragnar and 14 other Vikings including 2 of his close friends Leif Erikson, Asni Ship Chest and his brother King Ecbert successfully set sail to explore the western lands. . Drifting at sea for two days, they finally reached the mainland, where they found an English monastery. Ragnar Lothbrok's Viking army captured so much wealth with such ease for the first time that they were delighted, they stormed the temple and killed all the monks. Ragnar was interested in a monk who made him a slave for his family and this monk later helped Ragnar a lot in his journey to find new lands.

        After returning to Ragnar, he met Olaf Haraldsson and he stole all the wealth that Ragnar Lothbrok brought back. Olaf Haraldsson is a cunning man who wants to kill Ragnar to consolidate his power. Olaf Haraldsson used his daughter to bribe King Ecbert to betray his brother, but King Ecbert did not do so partly because King Ecbert was a good man, partly because he loved his brother's wife. Unable to harm Ragnar, Olaf Haraldsson angrily sent henchmen to kill all the people in Ragnar's village. Fortunately, Ragnar's whole family escaped, but Ragnar was badly injured and was helped by Bishop Heahumund, so he survived. A few days later Olaf Haraldsson captured Ragnar's brother to force him to appear, there was no way Ragnar sent a challenge to Olaf Haraldsso and promised to duel him three days later. Wishing to quickly kill Ragnar, Olaf Haraldsso accepted the challenge. In this battle, although wounded, Ragnar somehow managed to kill Olaf Haraldsson and successfully became the tribe's leader.

        After becoming the leader of Ragnar successfully gained the trust of the whole tribe to bring the most powerful Viking warriors to attack most of the countries in Europe, making these countries afraid. Later, descendants of King Ragnar Lothbrok, Halfdan the Black and Prince Fortress, respectively became kings of present-day Norway and Canada.

    </p>
</div>