<section id="home-tern-of-use" class="home-tern-of-use -bg-fix">
    <h2 id="title_page">Terms of Use</h2>
    <hr>
        <p>
            The terms of this agreement ("Terms of Service") govern the relationship between you and vikingdom, with the experience and long-standing technical team that delivered the product (hereinafter "vikingdom" or "them") me" or "We") regarding your use of vikingdom's games, websites and related services ("Services").
            <p>Use of the Service is also governed by vikingdom's Privacy Policy and other relevant policies, which are included here for your reference.
            Before accessing or using the Service, including browsing any vikingdom website or accessing a game, you must agree to these Terms of Service and the Privacy Policy.
            <p>You may also be required to register an account on the Service (an "Account"). By registering for an Account or otherwise using the Service, you represent that you are age 13 or older. If you are between the ages of 13 and 17, you represent that your legal guardian has reviewed and agreed to these Terms. If you access the Service from a Social Networking Site ("SNS"), such as Facebook or Google+, you shall comply with its terms of service/use as well as these Terms of Service.
            <p>BY INSTALLING, USING OR OTHERWISE ACCESSING THE SERVICE, YOU AGREE TO THESE TERMS OF SERVICE. IF YOU DO NOT AGREE TO THESE TERMS OF SERVICE, PLEASE DO NOT INSTALL, USE OR OTHERWISE ACCESS THE SERVICE. USE OF THE SERVICE IS VOID WHERE PROHIBITED.
            <p>Vikingdom reserves the right, at its discretion, to change, modify, add or remove portions of these Terms of Service,  its Privacy Policy and other relevant vikingdom policies at any time by posting the amended terms on the vikingdom Service. You will be deemed to have accepted such changes by continuing to use the Service. If at any point you do not agree to any portion of the then-current version of our Terms of Service, the vikingdom Privacy Policy, or any other vikingdom policy, rules or codes of conduct relating to your use of the Service, your license to use the Service shall immediately terminate, and you must immediately stop using the Service.
        <h3>1. License</h3>
        <h4>1.1. Grant of a Limited License to Use the Service</h4>
            <p>Subject to your agreement and continuing compliance with these Terms of Service and any other relevant vikingdom policies, vikingdom grants you a non-exclusive, non-transferable, non-sublicensable, revocable and limited license to access and use the Service for your own non-commercial entertainment purposes. You agree not to use the Service for any other purpose.
                The following restrictions apply to the use of the Service:</p>
            <p>You shall not create an Account or access the Service if you are under the age of 13; You shall restrict use by minors, and you will deny access to children under the age of 13. You accept full responsibility for any unauthorized use of the Service by minors.
    <p>You are responsible for any use of your credit card or other payment instrument (e.g. metamask) by minors.
            You shall not (or attempt to) purchase, sell, rent or give away your Account, create an Account using a false identity or information, or on behalf of someone other than yourself; You shall not use the Service if you have previously been removed by vikingdom, or previously been banned from playing any vikingdom game.
            <p>You shall use your Account only for non-commercial purposes; You shall not use the Service to advertise, or solicit, or transmit any commercial advertisements, including chain letters, junk or spam e-mail or repetitive or misleading messages to anyone.
            Login information and Your Account
            You may be required to select a password for your Account or you may also use other credentials to access the Account ("Login Information").
        <p>You shall not share the Account or the Login Information, nor let anyone else access your Account or do anything else that might jeopardize the security of your Account. In the event you become aware of or reasonably suspect any breach of security, including without limitation any loss, theft, or unauthorized disclosure of the Login Information, you must immediately notify vikingdom and modify your Login Information.
            <p>You are solely responsible for maintaining the confidentiality of the Login Information, and you will be responsible for all uses of the Login Information, including purchases, whether or not authorized by you. You are responsible for anything that happens through your Account.
            vikingdom reserves the right to remove or reclaim any usernames at any time and for any reason, including but not limited to claims by a third party that a username violates the third party's rights.
            The Service supports only one Account per game on a supported device.
            License Limitations
            <p>Any use of the Service in violation of these License Limitations is strictly prohibited, can result in the immediate revocation of your limited license and may subject you to liability for violations of law.
            You agree that you will not, under any circumstances:
            Engage in any act that vikingdom deems to be in conflict with the spirit or intent of the Service or make improper use of vikingdom's support services.
            <p>Use or take part (directly or indirectly) in the use of cheats, exploits, automation software, bots, hacks, mods or any unauthorized third-party software designed to modify or interfere with the Service, any vikingdom game or any vikingdom game experience.
            <p>Modify or cause to be modified any files that are a part of the Service or any vikingdom game without vikingdom's express written consent.
            Disrupt, interfere with or otherwise adversely affect the normal flow of the Service or otherwise act in a manner that may negatively affect other users' experience when using the Service or playing vikingdom's games. This includes win trading and any other kind of manipulation of rankings, taking advantage of errors in the Service to gain an unfair edge over other players and any other act that intentionally abuses or goes against the design of the Service.
            Disrupt, overburden, or aid or assist in the disruption or overburdening of any computer or server ("Server") used to offer or support the Service or any vikingdom game environment.
            Institute, assist, or become involved in any type of attack, including without limitation distribution of a virus, denial of service attacks upon the Service, or other attempts to disrupt the Service or any other person's use or enjoyment of the Service.
            <p>Attempt to gain unauthorized access to the Service, Accounts registered to others or to the computers, Servers, or networks connected to the Service by any means other than the user interface provided by vikingdom, including but not limited to, by circumventing or modifying, attempting to circumvent or modify, or encouraging or assisting any other person to circumvent or modify, any security, technology, device, or software that is part of the Service.
            Post any information that is abusive, threatening, obscene, defamatory, libelous, or racially, sexually, religiously, or otherwise objectionable or offensive or engage in ongoing toxic behavior, such as by repeatedly posting information on an unsolicited basis.
            Post any information that contains nudity, excessive violence, or offensive subject matter or that contains a link to such content.
            <p>Attempt to, or harass, abuse, or harm, or advocate or incite harassment, abuse, or harm of another person, group, including vikingdom employees, including vikingdom's customer service representatives.
            Make available through the Service any material or information that infringes any copyright, trademark, patent, trade secret, right of privacy, right of publicity, or other right of any person or entity or impersonates any other person, including without limitation a vikingdom employee.
            <p>Reverse engineer, decompile, disassemble, decipher or otherwise attempt to derive the source code for any underlying software or other intellectual property used to provide the Service or any vikingdom game, or to obtain any information from the Service or any vikingdom game using any method not expressly permitted by vikingdom.
            <p>Solicit or attempt to solicit Login Information or any other login credentials or personal information from other users of the Service or any vikingdom game.
            Collect or post anyone's private information, including personally identifiable information (whether in text, image or video form), identification documents, or financial information through the Service.
            vikingdom reserves the right to determine what conduct it considers to be in violation of the rules of use or otherwise outside the intent or spirit of these Terms of Service or the Service itself. vikingdom reserves the right to take action as a result, which may include terminating your Account and prohibiting you from using the Service in whole or in part.
           <h4>1.2. Suspension and Termination of Account and Service</h4>
            <p>WITHOUT LIMITING ANY OTHER REMEDIES, vikingdom MAY LIMIT, SUSPEND, TERMINATE, MODIFY, OR DELETE ACCOUNTS OR ACCESS TO THE SERVICE OR PORTIONS THEREOF IF YOU ARE, OR vikingdom SUSPECTS THAT YOU ARE, FAILING TO COMPLY WITH ANY OF THESE TERMS OF SERVICE OR FOR ANY ACTUAL OR SUSPECTED ILLEGAL OR IMPROPER USE OF THE SERVICE, WITH OR WITHOUT NOTICE TO YOU. YOU CAN LOSE YOUR USER NAME AND PERSONA IN THE SERVICE AS A RESULT OF ACCOUNT TERMINATION OR LIMITATION, AS WELL AS ANY BENEFITS, PRIVILEGES, EARNED ITEMS AND PURCHASED ITEMS ASSOCIATED WITH YOUR USE OF THE SERVICE, AND vikingdom IS UNDER NO OBLIGATION TO COMPENSATE YOU FOR ANY SUCH LOSSES OR RESULTS.
            WITHOUT LIMITING OUR OTHER REMEDIES, WE MAY LIMIT, SUSPEND OR TERMINATE THE SERVICE AND USER ACCOUNTS OR PORTIONS THEREOF, PROHIBIT ACCESS TO OUR GAMES AND SITES, AND THEIR CONTENT, SERVICES AND TOOLS, DELAY OR REMOVE HOSTED CONTENT, AND TAKE TECHNICAL AND LEGAL STEPS TO PREVENT USERS FROM ACCESSING THE SERVICE IF WE BELIEVE THAT THEY ARE CREATING RISK OR POSSIBLE LEGAL LIABILITIES, INFRINGING THE INTELLECTUAL PROPERTY RIGHTS OF THIRD PARTIES, OR ACTING INCONSISTENTLY WITH THE LETTER OR SPIRIT OF OUR TERMS OR   POLICIES. ADDITIONALLY, WE MAY, IN APPROPRIATE CIRCUMSTANCES AND AT OUR SOLE DISCRETION, SUSPEND OR TERMINATE ACCOUNTS OF USERS WHO MAY BE REPEAT INFRINGERS OF THIRD PARTY INTELLECTUAL PROPERTY RIGHTS.
            vikingdom RESERVES THE RIGHT TO TERMINATE ANY ACCOUNT THAT HAS BEEN INACTIVE FOR 180 DAYS.
            vikingdom reserves the right to stop offering and/or supporting the Service or a particular game or part of the Service at any time, at which point your license to use the Service or a part thereof will be automatically terminated. In such event, vikingdom shall not be required to provide refunds, benefits or other compensation to users in connection with such discontinued Service .
             <p> Termination of your Account can include disabling your access to the Service or any part thereof including any content you submitted or others submitted.
            <p>You may terminate your Account at any time and for any reason by following the process described on our support page located at https://contact@vikingdom.io/ informing vikingdom that you wish to terminate your Account.
            <h3>2. Ownership</h3>
            <h4>2.1. Games and Service</h4>
    <p>All rights, title and interest in and to the Service (including without limitation any games, titles, computer code, themes, objects, characters, character names, stories, dialogue, catch phrases, concepts, artwork, animations, sounds, musical compositions, audio-visual effects, methods of operation, moral rights, documentation, in-game chat transcripts, character profile information, recordings of games played using a vikingdom game client, and the vikingdom game clients and server software) are owned by vikingdom. vikingdom reserves all rights, including without limitation, all intellectual property rights or other proprietary rights, in connection with its games and the Service.
            <h4>2.2. Accounts</h4>
    <p>NOTWITHSTANDING ANYTHING TO THE CONTRARY HEREIN, YOU ACKNOWLEDGE AND AGREE THAT YOU SHALL HAVE NO OWNERSHIP OR OTHER PROPERTY INTEREST IN THE ACCOUNT, AND YOU FURTHER ACKNOWLEDGE AND AGREE THAT ALL RIGHTS IN AND TO THE ACCOUNT ARE AND SHALL FOREVER BE OWNED BY AND INURE TO THE BENEFIT OF vikingdom.
            <h4>2.3. Virtual Items</h4>
    <p>vikingdom owns, has licensed, or otherwise has rights to use all of the content that appears in the Service or in vikingdom games. Notwithstanding any provision to the contrary herein, you agree that you have no right or title in or to any content that appears in the Service, including without limitation the virtual goods or currency appearing or originating in any vikingdom game, whether earned in a game or purchased from vikingdom, or any other attributes associated with an Account or stored on the Service.
            <h3>3. User Content</h3>
            <h4>3.1. Submission of User Content</h4>
            <p>"User Content" means any communications, images, sounds, and all the material, data, and information that you upload or transmit through a vikingdom game client or the Service, or that other users upload or transmit, including without limitation any chat text. By transmitting or submitting any User Content while using the Service, you affirm, represent and warrant that such transmission or submission is (a) accurate and not confidential or misleading; (b) not in violation of any laws, contractual restrictions or other third party rights, and that you have permission from any third party whose personal information or intellectual property is comprised in the User Content; (c) free of viruses, adware, spyware, worms or other malicious code; and (d) you acknowledge and agree that any of your personal information within such content will at all times be processed by vikingdom in accordance with its Privacy Policy.
           <h4> 3.1.1. Content Screening</h4>
    <p>vikingdom assumes no responsibility for the conduct of any user submitting any User Content, and assumes no responsibility for monitoring the Service for inappropriate content or conduct. We do not, and cannot, pre-screen or monitor all User Content. Your use of the Service is at your own risk. By using the Service, you may be exposed to User Content that is offensive, indecent or otherwise not in line with your expectations. You bear all risks associated with the use of any User Content available in connection with the Service. At our discretion, our representatives or
            technology may monitor and/or record your interaction with the Service or communications (including without limitation chat text) when you are using the Service.
            By entering into these Terms of Service, you hereby provide your irrevocable consent to such monitoring and recording. You acknowledge and agree that you have no expectation of privacy concerning the transmission of any User Content, including without limitation chat text or voice communications.
            vikingdom reserves the right in its sole discretion to review, monitor, prohibit, edit, delete, disable access to or otherwise make unavailable any User Content (including without limitation your User Content) without notice for any reason or for no reason at any time. If at any time vikingdom chooses, in its sole discretion, to monitor the Service, vikingdom nonetheless assumes no responsibility for User Content and assumes no obligation to modify or remove any inappropriate User Content. We have the right, but not the obligation, in our sole discretion to edit, refuse to post, or remove any User Content.
            <h4>3.2. Information Use by Other Members of the Service</h4>
    <h4>3.2.1. Public Discourse</h4>
    <p>The Service may include various forums, blogs and chat features where you can post User Content, including your observations and comments on designated topics. vikingdom cannot guarantee that other members will not use the ideas and information that you share. Therefore, if you have an idea or information that you would like to keep confidential and/or don't want others to use, do not post it on the Service. vikingdom shall have no responsibility to evaluate, use or compensate you for any ideas or information you may choose to submit.
    <h4>3.2.2. Responsible For Your Own Content</h4>
            <p>You are solely responsible for the information that you post on, through or in connection with the Service and that you provide to others. vikingdom may reject, refuse to post or delete any User Content for any or no reason, including, but not limited to, User Content that in the sole judgment of vikingdom violates these Terms of Service.
            <h4>3.2.3. Your License to vikingdom</h4>
            <p>You hereby grant to vikingdom an irrevocable, perpetual, transferable, fully paid-up, royalty-free, worldwide license (including the right to sublicense and assign to third party) and right to copy, reproduce, fix, adapt, modify, create derivative works from, manufacture, commercialize, publish, distribute, sell, license, sublicense, transfer, lease, transmit, publicly display, publicly perform, or provide access to electronically, broadcast, communicate to the public by telecommunication, display, perform, enter into computer memory, and use and practice, in any way, your User Content as well as all modified and derivative works thereof in connection with our provision of the Service, including marketing and promotions of the Service. You also hereby grant to vikingdom the right to authorize others to exercise any of the rights granted to vikingdom under these Terms of Service. You further hereby grant to vikingdom the unconditional, irrevocable right to use and exploit your name, likeness and any other information or material included in any User Content and in connection with any User Content, without any obligation to you. Except as prohibited by law, you waive any rights of attribution and/or any moral rights you may have in your User Content, regardless of whether your User Content is altered or changed in any manner. vikingdom does not claim any ownership rights in your User Content and nothing in these Terms of Service is intended to restrict any rights that you may have to use and exploit your User Content. vikingdom has no obligation to monitor or enforce your intellectual property rights in or to your User Content.
    <h4>3.3. User Interactions</h4>
            <p>You are solely responsible for your interactions with other users of the Service and any other parties with whom you interact through the Service and/or vikingdom games. vikingdom reserves the right, but has no obligation, to become involved in any way with these disputes. You will fully cooperate with vikingdom to investigate any suspected unlawful, fraudulent or improper activity, including, without limitation, granting vikingdom access to any password-protected portions of your Account.
            <p>If you have a dispute with one or more users, you release us (and our officers, directors, agents, subsidiaries, joint ventures and employees) from claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with such disputes.
    <h4>4. Fees and Purchase Terms</h4>
    <h4>4.1.Purchases</h4>
            <p>In the Service you may purchase, with "real world" money, a limited, personal, non-transferable, non-sublicensable, revocable license to use (a) "virtual currency", including but not limited to virtual cash , all for use in vikingdom games; (b) "virtual in-game items" (together with "virtual currency", "Virtual Items"); and (c) other goods or services ("Merchandise"). You are only allowed to purchase Virtual Items from us or our authorised partners through the Service, and not in any other way.
            vikingdom may manage, regulate, control, modify or eliminate Virtual Items and/or Merchandise at any time, with or without notice. vikingdom shall have no liability to you or any third party in the event that vikingdom exercises any such rights.
            The transfer of Virtual Items and Merchandise is prohibited except where expressly authorized in the Service. Other than as expressly authorized in the Service, you shall not sell, purchase, redeem or otherwise transfer Virtual Items or Merchandise to any person or entity or attempt any of the aforesaid, including but not limited to vikingdom, another user or any third party.
            ALL PURCHASES AND REDEMPTIONS OF VIRTUAL ITEMS MADE THROUGH THE SERVICE ARE FINAL AND NON-REFUNDABLE.
            The provision of Virtual Items for use in vikingdom games is a service provided by vikingdom that commences immediately upon acceptance by vikingdom of your purchase. Any refund abuse in games will lead to account termination.
            <h4>4.2. Payment of Fees<h4></h4>
            <p>You agree to pay all fees and applicable taxes incurred by you or anyone using an Account registered to you. vikingdom may revise the pricing for the goods and services offered through the Service at any time. YOU ACKNOWLEDGE THAT vikingdom IS NOT REQUIRED TO PROVIDE A REFUND FOR ANY REASON, AND THAT YOU WILL NOT RECEIVE MONEY OR OTHER COMPENSATION FOR UNUSED VIRTUAL ITEMS WHEN AN ACCOUNT IS CLOSED, WHETHER SUCH CLOSURE WAS VOLUNTARY OR INVOLUNTARY.
        <h3>5. Updates to the Service</h3>
            <p>You understand that the Service is an evolving one. vikingdom may require that you accept updates to the Service and to vikingdom's games you have installed on your device or computer. You acknowledge and agree that vikingdom may update the Service and vikingdom games, with or without notifying you. You may need to update third party software from time to time in order to receive the Service and play vikingdom games.
        <h3>6. Warranty disclaimer</h3>
        <p>WITHOUT LIMITATION OF vikingdom's LEGAL LIABILITY UNDER SECTION 7 BELOW, THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS FOR YOUR USE, WITHOUT WARRANTIES OF ANYTHING, WHAT. IMPLIED, INCLUDING WITHOUT LIMITATION OF WARRANTIES OF WORKABILITY, SPECIFIC PURPOSE, PURPOSE, NO VIOLATION AND WHAT IS FINDED FROM BUSINESS OR COMMERCIAL USE COURSE. vikingdom DOES NOT GUARANTEE THAT YOU WILL ACCESS OR USE THE SERVICES BY TIME OR LOCATION YOU CHOOSE; THAT THE SERVICE WILL BE NO CONTINUOUS OR ERROR; ERROR WILL BE CORRECTED; OR THAT THE GAME OR SERVICE HAS NO VIRUS OR OTHER HARMFUL INGREDIENTS. Some jurisdictions do not allow the exclusion of certain warranties. As a result, some of the disclaimers above may not apply to you.
        <h3>7. Limitation of liability; Unique and exclusive measurement; Compensation</h3>
        <p>FOR THE MAXIMUM EXCEPTION ALLOWED BY LAW, vikingdom WILL NOT BE LIABLY RESPONSIBLE TO YOU FOR ANY POSSIBILITY, ANYTHING, CONSEQUENCES, CONSEQUENCES, RESULTS, NO WAR PROFIT, LOSE PROFIT OR OTHER LOSE OF PROFITS, LOSSES however), OUTSIDE ORDERING OR INTERESTED IN ANY OTHER HUGE LOSS IT IS BASIS ON CONTRACT AND DISTRIBUTION ANOTHER OR IS NOT THE POSSIBILITY OF DAMAGE IT. OTHER OUT OF PROHIBITED BY LAW, vikingdom WILL NOT BE LIABILITY TO YOU MORE THAN THE AMOUNT YOU PAY TO VIKINGDOM BY THIS TERMS OF SERVICE FOR SIX (6) MONTHS AFTER CREATION. YOU CONFIRM AND AGREE THAT IF YOU HAVE NOT PAYED ANYTHING TO VIKINGDOM IN THIS TIME, YOU ARE ONLY FORWARDING (and vikingdom's exclusive liability) FOR ANY SUBJECTS AND CANCEL YOUR ACCOUNT.
            NOTHING IN THIS TERMS OF SERVICE WILL EFFECT THE RIGHTS AND STATUS OF ANY CONSUMER OR EXCLUSIVE OR LIMITATION OF ANY LIABILITY OF THE LIBRARY TO ANY CONSUMER OR EXCLUSIVELY FOR ANY DAMAGE OR PERSONAL DAMAGE ARRIVING FROM ANY MEMORY.
            You agree to indemnify, defend and hold vikingdom (and our officers, directors, agents, subsidiaries, joint ventures and employees) harmless from any and all claims, claims , damages, any other harm or loss, including reasonable attorneys' fees, asserted by any third party from or arising out of your use of the Service, or any other your breach of these Terms of Service, however the foregoing does not apply if the breach was not caused by your willful or negligent act.
        <h3>8. Dispute Resolution and Law</h3>
        <p>Should a dispute arise between you and vikingdom, we strongly encourage you to contact us directly first to seek a resolution by visiting our customer support website at https://vikingdom. io/. If you are a resident of the United States, these Terms of Service and any dispute arising out of or relating to these Terms or the Privacy Policy or the Service will be governed in all respects. side of the law. The law of California, notwithstanding its conflict of law provisions. You agree that any claim or dispute you may have against vikingdom will be resolved https://contact@vikingdom.io/ If you are a resident outside of the United States, notwithstanding its conflict of rules legislation. You agree that any claim or dispute you may have against vikingdom shall be exclusively resolved by vikingdom.
        <h3>9. Severability</h3>
        <p>You and vikingdom agree that if any portion of these Terms of Service or of the vikingdom Privacy Policy is found illegal or unenforceable, in whole or in part by any court of competent jurisdiction, such provision shall, as to such jurisdiction, be ineffective solely to the extent of such determination of invalidity or unenforceability without affecting the validity or enforceability thereof in any other manner or jurisdiction and without affecting the remaining provisions of the terms, which shall continue to be in full force and effect.
        <h3>10. General Provisions</h3>
            <h4>10.1. Assignment</h4>
        <p>vikingdom may assign or delegate these Terms of Service and/or the vikingdom Privacy Policy, in whole or in part, to any person or entity at any time with or without your consent. You may not assign or delegate any rights or obligations under the Terms of Service or Privacy Policy without vikingdom's prior written consent, and any unauthorized assignment and delegation by you is ineffective.
        <h4>10.2. Supplemental Policies</h4>
        <p>vikingdom may publish additional policies related to specific services such as forums, contests or loyalty programs. Your right to use such services is subject to those specific policies and these Terms of Service.
        <h4>10.3. Entire Agreement</h4>
        <p>These Terms of Service, any supplemental policies and any documents expressly incorporated by reference herein (including the vikingdom Privacy Policy), contain the entire understanding of you and vikingdom, and supersede all prior understandings of the parties hereto relating to the subject matter hereof, whether electronic, oral or written, or whether established by custom, practice, policy or precedent, between you and us with respect to the Service.
        <h4>10.4. No Waiver</h4>
        <p>The failure of vikingdom to require or enforce strict performance by you of any provision of these Terms of Service or the vikingdom Privacy Policy or failure to exercise any right under them shall not be construed as a waiver or relinquishment of vikingdom's right to assert or rely upon any such provision or right in that or any other instance.
            The express waiver by vikingdom of any provision, condition, or requirement of these Terms of Service or the vikingdom Privacy Policy shall not constitute a waiver of any future obligation to comply with such provision, condition or requirement.
            Except as expressly and specifically set forth in this these Terms of Service, no representations, statements, consents, waivers, or other acts or omissions by vikingdom shall be deemed a modification of these Terms of Service nor legally binding, unless documented in physical writing, hand signed by You and a duly appointed officer of vikingdom.
        <h4>10.5. Equitable Remedies</h4>
        <p>You acknowledge that the rights granted and obligations made under these Terms of Service to vikingdom are of a unique and irreplaceable nature, the loss of which shall irreparably harm vikingdom and which cannot be replaced by monetary damages alone so that vikingdom shall be entitled to injunctive or other equitable relief (without the obligations of posting any bond or surety or proof of damages) in the event of any breach or anticipatory breach by you.
        <p>You irrevocably waive all rights to seek injunctive or other equitable relief, or to enjoin or restrain the operation of the Service or any vikingdom game, exploitation of any advertising or other materials issued in connection therewith, or exploitation of the Service or any content or other material used or displayed through the Service and agree to limit your claims to claims for monetary damages, limited by Section 7 (if any).
        <h4>10.6. Force Majeure</h4>
        <p>vikingdom shall not be liable for any delay or failure to perform resulting from causes outside the reasonable control of vikingdom, including without limitation any failure to perform hereunder due to unforeseen circumstances or cause beyond vikingdom's control such as acts of God, war, terrorism, riots, embargoes, acts of civil or military authorities, fire, floods, accidents, strikes, or shortages of transportation facilities, fuel, energy, labor or materials.
        </p>
</section>
